export const PortfolioData = [
  {
    date: "2024-07-08",
    stockSymbol: "GOLDIAM",
    action: "Buy",
    quantity: 50,
    price: 178,
    notes: "SWING",
  },
  {
    date: "2024-07-08",
    stockSymbol: "LUPIN",
    action: "Buy",
    quantity: 5,
    price: 1783,
    notes: "SWING",
  },
  {
    date: "2024-07-08",
    stockSymbol: "SHALBY",
    action: "Buy",
    quantity: 30,
    price: 320,
    notes: "SWING",
  },
  {
    date: "2024-07-08",
    stockSymbol: "MPHASIS",
    action: "Buy",
    quantity: 4,
    price: 2645,
    notes: "SWING",
  },
  {
    date: "2024-07-08",
    stockSymbol: "GLENMARK",
    action: "Buy",
    quantity: 7,
    price: 1350,
    notes: "SWING",
  },
  {
    date: "2024-07-08",
    stockSymbol: "IRCON",
    action: "Buy",
    quantity: 30,
    price: 329,
    notes: "SWING",
  },
  {
    date: "2024-07-08",
    stockSymbol: "THERMAX",
    action: "Buy",
    quantity: 2,
    price: 5750,
    notes: "SWING",
  },
  {
    date: "2024-07-08",
    stockSymbol: "HCC",
    action: "Buy",
    quantity: 200,
    price: 49.4,
    notes: "3MONTHS",
  },
  {
    date: "2024-07-08",
    stockSymbol: "MIDHANI",
    action: "Buy",
    quantity: 20,
    price: 520,
    notes: "SWING",
  },
  {
    date: "2024-07-08",
    stockSymbol: "BHEL",
    action: "Buy",
    quantity: 30,
    price: 320.8,
    notes: "SWING",
  },
];
